server:
  port : 8077

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/modsen_test_task
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show_sql: true
  h2:
    console:
      enabled: true


